/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "kronos_core.h"


#define STM32L4_PERIPH_BASE     0x40000000UL
#define STM32L4_AHB2PERIPH_BASE 0x48000000UL
#define STM32L4_RCC_BASE        (STM32L4_PERIPH_BASE + 0x00021000UL)
#define STM32L4_GPIOA_BASE      (STM32L4_AHB2PERIPH_BASE + 0x0000UL)

#define REG32(address) (*(volatile uint32_t *)(address))

#define RCC_AHB2ENR REG32(STM32L4_RCC_BASE + 0x4CUL)
#define GPIOA_MODER REG32(STM32L4_GPIOA_BASE + 0x00UL)
#define GPIOA_ODR   REG32(STM32L4_GPIOA_BASE + 0x14UL)

#define GPIOA_ENABLE_BIT (1UL << 0)
#define LD2_PIN          5U
#define LD2_MASK         (1UL << LD2_PIN)
#define BLINK_COMMAND_MESSAGE_ID 1U
#define BLINK_TASK_STACK_WORDS 64U

static kronos_ingress_t g_blinkExecutionIngress;


static void board_led_init(void)
{
	RCC_AHB2ENR |= GPIOA_ENABLE_BIT;
	(void)RCC_AHB2ENR;

	GPIOA_MODER &= ~(3UL << (LD2_PIN * 2U));
	GPIOA_MODER |= 1UL << (LD2_PIN * 2U);
	GPIOA_ODR &= ~LD2_MASK;
}

static void board_led_toggle(void)
{
	GPIOA_ODR ^= LD2_MASK;
}

static void board_led_set(uint8_t enabled)
{
	if (enabled != 0U)
	{
		GPIOA_ODR |= LD2_MASK;
	}
	else
	{
		GPIOA_ODR &= ~LD2_MASK;
	}
}

static void blink_execution_task(void)
{
	uint8_t blink_enabled = 0U;
	kronos_mail_t mail;
	int32_t status;

	for (;;)
	{
		status = RTOS_IngressReceive(&mail);
		if ((status == KRONOS_STATUS_OK) && (mail.payload_size > 0U))
		{
			blink_enabled = (mail.payload[0] != 0U) ? 1U : 0U;
		}

		if (blink_enabled != 0U)
		{
			board_led_toggle();
		}
		else
		{
			board_led_set(0U);
			
		}

		RTOS_Delay(50U);
	}
}

static void blink_commanding_task(void)
{
	uint8_t led_state = 0U;
	int32_t status;

	status = RTOS_IngressResolve(&g_blinkExecutionIngress, "blink_exec");
	if (status != KRONOS_STATUS_OK)
	{
		for (;;)
		{
			RTOS_Delay(1000U);
		}
	}

	for (;;)
	{
		led_state ^= 1U;
		(void)RTOS_EgressSend(&g_blinkExecutionIngress, BLINK_COMMAND_MESSAGE_ID, &led_state, (uint32_t)sizeof(led_state));
		RTOS_Delay(1000U);
	}
}



int main(void)
{
	board_led_init();

	RTOS_Init();

	if (RTOS_CreateTask(blink_execution_task, BLINK_TASK_STACK_WORDS, "blink_exec") < 0)
	{
		for (;;)
		{
			// Task creation failed. Stay here.
		}
		/* Unreachable. */
	}

	if (RTOS_CreateTask(blink_commanding_task, BLINK_TASK_STACK_WORDS, "blink_cmd") < 0)
	{
		for (;;)
		{
			// Task creation failed. Stay here.
		}
		/* Unreachable. */
	}

	RTOS_Start();

	for (;;)
	{
		// Should never reach here.
	}
}
